apiVersion: v1
kind: Service
metadata:
  name: wazuh 
  namespace: default
  labels:
    app: wazuh-manager
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: communication
      port: 1514
      targetPort: 1514
    - name: api
      port: 55000
      targetPort: 55000
