apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    app: es-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: es-service
  ports:
  - name: es-mainport
    port: 9200
    protocol: TCP
  - name: es-workerport
    port: 9300
    protocol: TCP
