ability_refresh: 60
api_key_blue: LuEXrcyb1qDWu0felY2HsNjMl71EPmHRmj7Ls2_NgJQ
api_key_red: QhhxR4RiScwb2-pZkWGkul9ZCmYOsaYCYdRkNcFGsAQ
app.contact.dns.domain: mycaldera.caldera
app.contact.dns.socket: 0.0.0.0:8853
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.tunnel.ssh.host_key_file: REPLACE_WITH_KEY_FILE_PATH
app.contact.tunnel.ssh.host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE
app.contact.tunnel.ssh.socket: 0.0.0.0:8022
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: s4ndc4t!
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
auth.login.handler.module: default
crypt_salt: CBjGQCaFpyM3imuyn_Ee5x-RbfwOdDQLuCv-60eMMlE
encryption_key: VPwyMkvk50pjd-rIYMCn4xon7vhTbRqB0SZhd7VfWSc
exfil_dir: /tmp/caldera
host: 0.0.0.0
plugins:
- access
- atomic
- compass
- debrief
- fieldmanual
- gameboard
- manx
- response
- sandcat
- stockpile
- training
port: 8888
reports_dir: /tmp
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.11
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.6.1
users:
  blue:
    blue: RpbAAWZEnRXrC3xBOuqn2z-2zhazIDWzwdZDjui2MtA
  red:
    red: B-edBDUNYhm9GUBvG3PhEdYq3vNG3Fzu0DRye5lzGXw
