apiVersion: v1
kind: Service
metadata:
  name: kibana 
  namespace: default
  labels:
    app: kibana
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: kibana-mainport
      port: 5601
      targetPort: 5601
